// angularapp/src/app/app.component.ts
import { Component } from '@angular/core';
import { loadImages } from 'src/api';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  isLoading = false;
  notificationText: string | null = null;
  images: Image[] = [];
  page = "home"
  searchParam = ""

  async search() {
    this.isLoading = true
    const response = await loadImages(this.searchParam)
    this.isLoading = false
    if (!response.success) {
      this.notificationText = response.error
    } else {
    const data = response.data
    this.images = data.map(img => ({...img, smallAmount: 0, largeAmount: 0}))
    this.notificationText = null
    }
  }
}

type Image = {
  id: number;
  title: string;
  url: string;
  smallAmount: number;
  largeAmount: number;
};

<div *ngIf="page === 'home'; else about">
  <h1>Home page</h1>
  <button (click)="page = 'about'">To about</button>
</div>

<ng-template #about>
  <div>
    <h1>About page</h1>
    <button (click)="page = 'home'">To home</button>
  </div>
</ng-template>

<input type="text" placeholder="Title" [(ngModel)]="searchParam">
<button (click)="searchParam = ''">Clear</button>
<button (click)="search()">Search</button>

<div *ngIf="isLoading">Loading...</div>

<div *ngFor="let image of images">
  <p>{{ image.title }}</p>
  <img src="{{ image.url }}" alt="{{ image.title }}" />
</div>

<h1 *ngIf="notificationText">{{ notificationText }}</h1>

// svelteapp/src/App.svelte
<script lang="ts">
  import { loadImages } from "./lib/api";

  type Image = {
    id: number;
    title: string;
    url: string;
    smallAmount: number;
    largeAmount: number;
  };

  let isLoading = false;
  let notificationText: string | null = null;
  let images: Image[] = [];

  let page = "home"

  let searchParam = ""

  const search = async () => {
    isLoading = true
    const response = await loadImages(searchParam)
    isLoading = false
    if (!response.success)
      return notificationText = response.error
    const data = response.data
    images = data.map(img => ({...img, smallAmount: 0, largeAmount: 0}))
    notificationText = null
  }

</script>

<main>
  <div class="card">

    {#if page === "home"}
      <div>
        <button on:click={() => page = "about"}>To about</button>
        <input type="text" placeholder="Title" bind:value={searchParam}>
        <button on:click={() => searchParam = ""}>Clear</button>
        <button on:click={search}>Search</button>

        {#if isLoading}
          <p>Loading...</p>
          {:else}
            
          {#each images as image}
            <p>{ image.title }</p>
            <img src={ image.url } alt={ image.title }>
          {/each}
        {/if}

        {#if notificationText}
          <h1>{ notificationText }</h1>
        {/if}

      </div> 
    {/if}

    {#if page === "about"}
      <div>
        <button on:click={() => page = "home"}>To Home</button>
      
      </div>
    {/if}

  </div>
</main>
